checking build

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -56,9 +56,17 @@ jobs:
 
             # Create a temporary .env file
             echo "Setting up environment variables..."
-            cat <<EOF > /tmp/.env
-            $(cat .env | xargs)
-            EOF
+            cat .env | xargs > /tmp/.env
+
+            # Check if the .env file was created successfully
+            if [ ! -f /tmp/.env ]; then
+                echo "Failed to create /tmp/.env"
+                exit 1
+            fi
+            
+            # Verify contents of the .env file
+            echo "Contents of /tmp/.env:"
+            cat /tmp/.env
 
             # Pull the latest Docker image from Docker Hub
             echo "Deploying Docker image with version ${{ env.VERSION }}..."
@@ -69,6 +77,7 @@ jobs:
             sudo docker rm test_app.dev || true
 
             # Run the new Docker container with the .env file
+            echo "Running Docker container with environment variables..."
             sudo docker run -d -p 3000:3000 --name test_app.dev --env-file /tmp/.env ${{ secrets.DOCKER_USERNAME }}/nestjs-app:${{ env.VERSION }}
             echo "Deployment complete."
 
